import type { PluginContracts } from './types';
import { contractsSchemaId, contractsVersion } from './version';

/**
 * AI Docs plugin contracts manifest
 * Level 2: Contracts типизация с as const для извлечения типов
 */
export const pluginContractsManifest = {
  schema: contractsSchemaId,
  pluginId: '@kb-labs/ai-docs',
  contractsVersion,
  artifacts: {
    'ai-docs.plan.json': {
      id: 'ai-docs.plan.json',
      kind: 'json',
      description: 'Documentation plan generated by ai-docs:plan',
      pathPattern: '.kb/ai-docs/plan.json',
      mediaType: 'application/json',
    },
    'ai-docs.drift.json': {
      id: 'ai-docs.drift.json',
      kind: 'json',
      description: 'Documentation drift analysis (JSON)',
      pathPattern: '.kb/ai-docs/drift.json',
      mediaType: 'application/json',
    },
    'ai-docs.drift.md': {
      id: 'ai-docs.drift.md',
      kind: 'markdown',
      description: 'Documentation drift analysis (Markdown)',
      pathPattern: '.kb/ai-docs/drift.md',
      mediaType: 'text/markdown',
    },
    'ai-docs.suggestions': {
      id: 'ai-docs.suggestions',
      kind: 'file',
      description: 'Documentation suggestions',
      pathPattern: '.kb/artifacts/ai-docs/suggestions',
    },
    'ai-docs.generated': {
      id: 'ai-docs.generated',
      kind: 'dir',
      description: 'Generated documentation files',
      pathPattern: '.kb/artifacts/ai-docs/generated',
    },
  },
  commands: {
    'ai-docs:init': {
      id: 'ai-docs:init',
      description: 'Create docs skeleton and aiDocs config section',
      examples: [
        'kb ai-docs init',
        'kb ai-docs init --docs-path docs/ai-docs --format mdx',
      ],
    },
    'ai-docs:plan': {
      id: 'ai-docs:plan',
      description: 'Generate documentation plan',
      examples: ['kb ai-docs plan'],
    },
    'ai-docs:generate': {
      id: 'ai-docs:generate',
      description: 'Generate documentation',
      examples: ['kb ai-docs generate'],
    },
    'ai-docs:audit': {
      id: 'ai-docs:audit',
      description: 'Audit documentation',
      examples: ['kb ai-docs audit'],
    },
  },
} as const satisfies PluginContracts;

// Извлекаем типы для использования в других местах
export type PluginArtifactIds = keyof typeof pluginContractsManifest.artifacts;
export type PluginCommandIds = keyof typeof pluginContractsManifest.commands;
