import { createManifestV2 } from '@kb-labs/plugin-manifest';
import { pluginContractsManifest } from '@kb-labs/ai-docs-contracts';

/**
 * Level 2: Типизация через contracts для автодополнения и проверки ID
 */
export const manifest = createManifestV2<typeof pluginContractsManifest>({
  schema: 'kb.plugin/2',
  id: '@kb-labs/ai-docs',
  version: '0.0.1',
  display: {
    name: 'KB Labs AI Docs',
    description: 'Bootstrap, plan, generate, and audit engineering documentation safely.',
    tags: ['docs', 'ai', 'workflow']
  },
  cli: {
    commands: [
      {
        id: 'init',
        group: 'ai-docs',
        describe: 'Create docs skeleton and aiDocs config section.',
        handler: './cli/commands/init/run#runInitCommand',
        flags: [
          { name: 'docs-path', type: 'string', description: 'Custom docs root (default docs/ai-docs)' },
          { name: 'format', type: 'string', description: 'md or mdx', choices: ['md', 'mdx'] },
          { name: 'language', type: 'string', description: 'Target language (default en)' },
          { name: 'json', type: 'boolean', description: 'Return JSON payload' }
        ]
      },
      {
        id: 'plan',
        group: 'ai-docs',
        describe: 'Analyse project inputs and emit plan.json + TOC.',
        handler: './cli/commands/plan/run#runPlanCommand',
        flags: [
          { name: 'profile', type: 'string', description: 'Profile ID' },
          { name: 'plan-path', type: 'string', description: 'Override plan output path' },
          { name: 'json', type: 'boolean', description: 'Return JSON payload' }
        ]
      },
      {
        id: 'generate',
        group: 'ai-docs',
        describe: 'Generate/update docs based on plan.json.',
        handler: './cli/commands/generate/run#runGenerateCommand',
        flags: [
          {
            name: 'strategy',
            type: 'string',
            choices: ['append', 'rewrite-section', 'suggest-only'],
            description: 'How to apply generated sections'
          },
          { name: 'profile', type: 'string', description: 'Profile ID' },
          { name: 'plan-path', type: 'string', description: 'Path to plan.json' },
          { name: 'sections', type: 'string', description: 'Comma-separated section IDs to limit scope' },
          { name: 'dry-run', type: 'boolean', description: 'Skip writes, produce diff artifacts' },
          { name: 'suggest-only', type: 'boolean', description: 'Write suggestions without touching docs' },
          { name: 'json', type: 'boolean', description: 'Return JSON payload' }
        ]
      },
      {
        id: 'audit',
        group: 'ai-docs',
        describe: 'Compute drift score and produce reports.',
        handler: './cli/commands/audit/run#runAuditCommand',
        flags: [
          { name: 'from', type: 'string', description: 'Git revision start' },
          { name: 'to', type: 'string', description: 'Git revision end' },
          { name: 'json', type: 'boolean', description: 'Return JSON payload' }
        ]
      }
    ]
  },
    permissions: {
      fs: {
        mode: 'readWrite',
        allow: ['docs/**', '.kb/**', 'kb.config.json'],
        deny: ['**/*.key', '**/*.secret']
      },
    net: 'none',
    env: {
      allow: ['NODE_ENV']
    },
    quotas: {
      timeoutMs: 240000,
      memoryMb: 256,
      cpuMs: 10000
    },
    capabilities: []
  },
  artifacts: [
    {
      id: 'ai-docs.plan.json',
      pathTemplate: '.kb/ai-docs/plan.json',
      description: 'Documentation plan generated by `kb ai-docs plan` with sections and gaps.',
    },
    {
      id: 'ai-docs.drift.json',
      pathTemplate: '.kb/ai-docs/drift.json',
      description: 'Drift analysis JSON report (generated by `kb ai-docs audit`).',
    },
    {
      id: 'ai-docs.drift.md',
      pathTemplate: '.kb/ai-docs/drift.md',
      description: 'Drift analysis Markdown report (generated by `kb ai-docs audit`).',
    },
    {
      id: 'ai-docs.suggestions',
      pathTemplate: '.kb/artifacts/ai-docs/suggestions/**',
      description: 'Documentation suggestions generated during `kb ai-docs generate` (when suggest-only mode).',
    },
    {
      id: 'ai-docs.generated',
      pathTemplate: 'docs/ai-docs/**',
      description: 'Generated documentation files (path configurable via config.output.basePath).',
    },
  ],
  setup: {
    handler: './setup/handler.js#run',
    describe: 'Provision AI Docs workspace defaults (profiles, config, scripts).',
    permissions: {
      fs: {
        mode: 'readWrite',
        allow: ['.kb/ai-docs/**', '.kb/artifacts/ai-docs/**', 'kb.config.json'],
        deny: ['.kb/plugins.json', '.kb/kb-labs.config.json', '.git/**']
      },
      net: 'none'
    }
  }
});

export default manifest;

