import type { MockLlmsPort } from '../../application/types.js';
import { buildSectionResult } from '../../domain/generation.js';

export function createMockLlms(): MockLlmsPort {
  return {
    async generateSections({ targetSections, profile }) {
      return {
        sections: targetSections.map((section) =>
          buildSectionResult({
            sectionId: section.id,
            targetPath: section.targetPath,
            strategy: 'append',
            status: 'created',
            confidence: 0.65,
            needsReview: false,
            note: `Mock content for ${section.title} (${profile ?? 'default'})`,
            content: [
              `# ${section.title}`,
              '',
              `> Generated by AI Docs mock profile: ${profile ?? 'default'}`,
              '',
              `This placeholder explains the **${section.id}** section.`,
              '',
              '- Replace this with real LLM output once providers are wired in.',
              '- Source data: plan + Mind summaries.'
            ].join('\n')
          })
        )
      };
    }
  };
}

